# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c69802fac815baa5eaf832520e8ceb7d6ec8d1c6198f313010c1c91eb3d6284bf1734d73c6bd870321fada1aeccd20c28d9b2001b8ca962aec94e333673e9a11

test:
  secret_key_base: 0c3ecc792241d20f0e07e0ae0b93ae7b83eb6d0d54e10a1050bc5bc6706dc32ff475d870ceb4f516328ff78796a4323fcbdf1fd1ac6708d7f69f799d4665ccb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
